### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by MarcoBuster** [tdlight-team/tdlight-telegram-bot-api#14]
I think we need to improve the documentation of this project. Having all the important stuff and the details together in the README is a bit messy and not clear to new users. Also, we should add more information and guides on how to build and deploy the package and be clear about the new features added to upstream.

To address this, we could use the integrated GitHub Wiki and link the pages in README but if you have another proposal please share it in comments. :+1:

**Comment by JosXa** [comment]
I wget'd the bot API docs to here: https://github.com/JosXa/telegram-bot-api-docs/tree/main/core.telegram.org/bots/api
Maybe we can just use that as a base for making a custom website for the docs in the regular bot API style?

**Comment by iiiiii1wepfj** [comment]
@JosXa cool now we can create a docs for tdlight

**Comment by MarcoBuster** [comment]
> I wget'd the bot API docs to here: [Repo](https://github.com/JosXa/telegram-bot-api-docs/tree/main/core.telegram.org/bots/api) / [GH Pages](https://josxa.github.io/telegram-bot-api-docs/core.telegram.org/bots/api)
> Maybe we can just use that as a base for making a custom website for the docs in the regular bot API style?

That documentation is provided without a license, so we must assume that's under full copyright with all rights reserved. We could ask Telegram the permission to use it, but I doubt they'll grant to us.

**Comment by andrew-ld** [comment]
can convert docs in json (using https://github.com/sys-001/tgbotapi-generator) and reconvert in markdown

**Comment by code1mountain** [comment]
My current idea for better documentation is using openAPI. We can generate the openAPI json/yaml file with this: https://github.com/ark0f/tg-bot-api from the telegram documentations. Then we can add our own endpoints and modifications to it. When there is an official new version of the bot api, we can merge the new generated version with our modified one.

Documenting with openAPI has the advantage, that we can generate swagger docs quite easily and also automatically generate a wrapper for it fully automatically.

**Comment by JosXa** [comment]
Trying out a couple of services (https://openapi.tools/#documentation) simultaneously, let's see if there's a cool free one otherwise we'll build it ourselves

- Official SwaggerHub Docs (https://app.swaggerhub.com/apis-docs/JosXa/telegram-bot_api/5.0.0) (collaborate (https://app.swaggerhub.com/apis/JosXa/telegram-bot_api/5.0.0))
- Bump.sh
 (https://bump.sh/doc/botapi)- Stoplight.io
 (https://josxa.stoplight.io/docs/bot-api/openapi.json)- apimatic.io (https://www.apimatic.io/api-docs/botapi) (click links in top right corner)

**Comment by JosXa** [comment]
@MarcoBuster 

> We could ask Telegram the permission to use it, but I doubt they'll grant to us.

You don't think? I doubt they care very much

**Comment by MarcoBuster** [comment]
@code1mountain talk about this page https://code1mountain.github.io/tdlight-telegram-bot-api-docs/.
How did you made it? I really like it

**Comment by MarcoBuster** [comment]
How did you generate the yaml file?

**Comment by MarcoBuster** [comment]
By the way, I'd like to separate the existing bot api features and ours. Is it possible in some way?

**Comment by code1mountain** [comment]
I used the latest version of the [generated](https://github.com/ark0f/tg-bot-api) openAPI docs from pages.pelme.ga/tg-bot-api and edited our own changes manually. Editing an openAPI yaml file can easily be done with https://editor.swagger.io/

I could remove all methods from the official bot api from the yaml file but if we would add a new parameter to an official method, we would need to add it back completely and check every update of the bot api how it has changed.

In the current state we could probably just merge a new generated yaml file with our yaml file to update it. All of our own methods are on the top.

**Comment by JosXa** [comment]
I imagine a nice workflow with GH actions that can make pull requests automatically when something changes in her repo and do not expect many merge conflicts or anything of the sort, as usually few additions or modifications get made, only additions.

**Comment by luckydonald** [comment]
@JosXa One way of handling upstream updates is we we could make a commit for the "original" documentation, and then add your additions in a separate commit.
 That way we could branch of that very first commit, update the file with changes from there, and hopefully do a clean merge.
