### ISSUE TITLE
Compatibility mode

### ISSUE THREAD

**Issue by luckydonald** [tdlight-team/tdlight-telegram-bot-api#27]
It might be useful to offer a command line flag (or per bot setting?) to have the API serve the updates conform to the standard, to make integrations with libraries as seamless as possible, and increase the drop-in ability.

**Comment by code1mountain** [comment]
This API is completely backwards compatible to the original bot api. Adding new stuff shouldn't break any library cause Telegram adds new objects all the time and just mentions them later in their changelog, we just shouldn't add any breaking changes.

**Comment by giuseppeM99** [comment]
Is not like we made breaking changes, i don't think that adding new fields would break anything

**Comment by luckydonald** [comment]
Okey, just wanted to have brought that up.
