### ISSUE TITLE
Fails if TELEGRAM_STAT is not set

### ISSUE THREAD

**Issue by noplanman** [tdlight-team/tdlight-telegram-bot-api#30]
For me, using docker, the container fails if the TELEGRAM_STAT variable isn't set.

Maybe because the healthcheck uses it but it's not available?

**Comment by MarcoBuster** [comment]
Can you send us the logs please?

**Comment by noplanman** [comment]
Hi @MarcoBuster, which logs?

When the container starts, the status is `starting` for a long time, then it says `unhealthy`. I can't connect to the API and simply get a "404 page not found".

The container logs only have a single line with the command for starting the API server, nothing more.

**Comment by MarcoBuster** [comment]
@noplanman set TELEGRAM_VERBOSITY=4 then the logs will appear. Without them we can't understand the problem.

**Comment by luckydonald** [comment]
@MarcoBuster Isn't the health check like a curl request to the stats port?

It simply says "curl -f http://localhost:8082/ || exit 1"
In the Dockerfile

Of cause that'll fail if there's no :8082 port serving the stats.
The locks would be the wrong place to look here anyway, and I think it's not needed; that's some simple logic error.
As we now have the ping command, we should use that one instead of the stats endpoint.

**Comment by luckydonald** [comment]
@luckydonald *logs
(Sorry am on mobile)

**Comment by giuseppeM99** [comment]
@luckydonald the ping command requires a valid token

**Comment by luckydonald** [comment]
@luckydonald Wait, we can't use a ping command as that is bound to a bot so we would need to add a bot token?

**Comment by luckydonald** [comment]
@luckydonald So to fix it properly, we should either so if the ping port without a token (unauthorized) as well.
Maybe for now, if the stats are not explicitly enabled they could be instead be enabled but bound to just the local network interface needed to get the curl request done?

**Comment by code1mountain** [comment]
@luckydonald Theoretically ping doesn't require a token, we could move the ping command out of there, but it is more confusing with the URL layout then.

**Comment by MarcoBuster** [comment]
...or we could just disable the health check if you don't have TELEGRAM_STAT set

**Comment by giuseppeM99** [comment]
@MarcoBuster is that even possible?

**Comment by MarcoBuster** [comment]
@giuseppeM99 I don't know, we should investigate

**Comment by giuseppeM99** [comment]
@MarcoBuster i'll fix it asap

**Comment by luckydonald** [comment]
Okey, just to give my two cents, maybe we should actually look into creating a real `/healtcheck` endpoint.
So if it does a ping or not, would be a implementation detail.
Maybe that could even be served at the root directly, doing a few non-critical stats there.
