### ISSUE TITLE
Update GitHub "About" section

### ISSUE THREAD

**Issue by JosXa** [tdlight-team/tdlight-telegram-bot-api#31]
Currently, the about section reads:

**About**
`The Telegram Bot API provides an HTTP API for creating Telegram Bots.`

I would suggest the following, tdlight-focused introduction:

**About**
`The TDLight Telegram API is an actively enhanced fork of the original Bot API, featuring experimental user support with strong focus on memory footprint and performance.`

**Comment by andrew-ld** [comment]
make a pr

**Comment by JosXa** [comment]
> make a pr

You can't PR the about description ;)

![Uploading image.png…]()

**Comment by skrtdev** [comment]
@JosXa Lol that’s tue
