### ISSUE TITLE
[Feature Request] Add toggleSlowmode method

### ISSUE THREAD

**Issue by MasterGroosha** [tdlight-team/tdlight-telegram-bot-api#34]
For some unknown reason, Telegram Bot API doesn't allow bots to toggle slowmode on or off. It would be very kind of TDLight team to add this custom method to your Bot API implementation.

https://core.telegram.org/method/channels.toggleSlowMode

**Comment by code1mountain** [comment]
@MasterGroosha The mtproto method to toggle slowmode is only available to users, not bots. We can create a method for users for sure.

**Comment by MasterGroosha** [comment]
Oh, my bad. Bots definitely cannot toggle slowmode now. Sorry!
