### ISSUE TITLE
Update td submodule

### ISSUE THREAD

**Issue by Cavallium** [tdlight-team/tdlight-telegram-bot-api#36]
Update td submodule and check if everything works with the new TDLib version.

**Comment by giuseppeM99** [comment]
@Cavallium or let's wait for levlam to update the upstream

**Comment by MarcoBuster** [comment]
I agree with @giuseppeM99. We have no rush

**Comment by luckydonald** [comment]
I'd be interested in layer 121.

**Comment by Cavallium** [comment]
If someone wants to work on the updated tdlib there's the branch td-171

**Comment by luckydonald** [comment]
is that number the layer?
