### ISSUE TITLE
API in user mode receives no updates for outgoing messages

### ISSUE THREAD

**Issue by JosXa** [tdlight-team/tdlight-telegram-bot-api#53]
When logging in as a user, `getUpdates` only yields updates for incoming messages, outgoing ones are ignored. This is most likely a "remnant" of the bots-only API and I assume the same holds true for webhooks. 

Without this feature, it makes creating /command-based userbots nearly impossible (as the program can't react to whatever you do in your normal Telegram application).

**Comment by penn5** [comment]
Duplicate of #32
