### ISSUE TITLE
PosixError : Permission denied : 13 : File "user_db.binlog" can't be opened/created for reading and writing

### ISSUE THREAD

**Issue by HitaloSama** [tdlight-team/tdlight-telegram-bot-api#64]
I'm using the Docker container and after updating it I had this error at container startup.

```bash
LOG:00000000:  [ 2][t 0][1624885451.285162925][telegram-bot-api.cpp:468]Bot API 5.3 server started            
LOG:00000070:  [ 2][t 0][1624885451.286713123][ClientManager.cpp:416][!ClientManager]Loaded 0 TQueue events   
LOG:000000e0:  [ 0][t 0][1624885451.286823987][ClientManager.cpp:442][!ClientManager][&status.is_error()]Can't open user_db.binlog [PosixError : Permission denied : 13 : File "user_db.binlog" can't be opened/created for reading and writing]              
[pid 1] [time 1624885451] ------------------------
```

**Comment by smaznet** [comment]
@HitaloSama chown -R -u 101 ./tworkdata

**Comment by HitaloSama** [comment]
> @HitaloSama chown -R -u 101 ./tworkdata

How can I run the command if the container is not running?

**Comment by giuseppeM99** [comment]
docker exec -it container_name /bin/sh

**Comment by noplanman** [comment]
I have the same problem. Even reverting to the previous version doesn't help, it's failing now too!

I've set the permissions, even tried to `chmod 777` to make sure it's not a permission problem, but still fails.

Any other ideas?

**Comment by Cavallium** [comment]
If you are not running anything critical you can do `chmod -R 777` but only as a temporary solution

**Comment by noplanman** [comment]
I've done that, same error 🤔

**Comment by giuseppeM99** [comment]
sorry for that, should be fixed in the next build

**Comment by noplanman** [comment]
Still curious why reverting to a previous version doesn't work.

My `user_db.binlog` file is an empty file, is that normal?

**Comment by giuseppeM99** [comment]
> Still curious why reverting to a previous version doesn't work.
> 
> My `user_db.binlog` file is an empty file, is that normal?

Yes if you don't use the user mode

**Comment by giuseppeM99** [comment]
hello, it is now released, you can `docker pull` or `docker-compose pull` and restart the container, if you haven't used the user mode and it still gives you permission issues you can delete the `user_db.binlog` file, it will be recreated with the appropriate permissions

**Comment by noplanman** [comment]
Perfect, it's working again, thanks for the speedy response 🙏

**Comment by Cavallium** [comment]
v5.3.1 includes this fix

**Comment by smaznet** [comment]
> > @HitaloSama chown -R -u 101 ./tworkdata
> 
> How can I run the command if the container is not running?

should be run on host machine
