### ISSUE TITLE
Running tdlight-telegram-bot-api via corporate HTTP proxy 

### ISSUE THREAD

**Issue by ipetrovmgn** [tdlight-team/tdlight-telegram-bot-api#80]
Is it possible to run [tdlight-telegram-bot-api](https://github.com/tdlight-team/tdlight-telegram-bot-api) via corporate proxy? 

Unfortunately original telegram-bot-api needs to modify source code in Client.cpp to work via proxy.  You have methods proxyTypeHttp proxyTypeMtproto proxyTypeSocks5  but how use them? Docker-entrypoint show TELEGRAM_PROXY option but it related to webhooks,
In the same time tdlight-api-openapi.yaml have options /addProxy via POST. Kindly please advice what should be done? Thanks!

**Comment by giuseppeM99** [comment]
You need to add a proxy first using the [addProxy](https://tdlight-team.github.io/tdlight-telegram-bot-api/#/added/post_addProxy) method, you'll get a `proxy_id`, use that id with the [enableProxy](https://tdlight-team.github.io/tdlight-telegram-bot-api/#/added/post_enableProxy) method to use it
Note that proxies are per bot and not for the whole botapi
